//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCar.mathsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mathsService.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebAdd", ReplyAction="*")]
        int WebAdd(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebAdd", ReplyAction="*")]
        System.Threading.Tasks.Task<int> WebAddAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebMultiply", ReplyAction="*")]
        int WebMultiply(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebMultiply", ReplyAction="*")]
        System.Threading.Tasks.Task<int> WebMultiplyAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : global::MyCar.mathsService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<global::MyCar.mathsService.WebService1Soap>, global::MyCar.mathsService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int WebAdd(int x, int y) {
            return base.Channel.WebAdd(x, y);
        }
        
        public System.Threading.Tasks.Task<int> WebAddAsync(int x, int y) {
            return base.Channel.WebAddAsync(x, y);
        }
        
        public int WebMultiply(int x, int y) {
            return base.Channel.WebMultiply(x, y);
        }
        
        public System.Threading.Tasks.Task<int> WebMultiplyAsync(int x, int y) {
            return base.Channel.WebMultiplyAsync(x, y);
        }
    }
}
